name: parse_json
on:
  issues:
    types: [opened, edited, milestoned]
  schedule:
    - cron: "0 * * * *"

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Update
      - uses: actions/checkout@v1
      - run: bash update.sh -xe
