name: update_json
on:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: macos-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Update json file
        run: bash update.sh -xe
      - name: Commit and Push
        run: |
          git config --global user.name 'Soh Satoh'
          git config --global user.email 'sohsatoh@users.noreply.github.com'
          git commit -am "Automated Update"
          git push
